---
# Add apt key
- name: add apt key
  sudo: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E56151BF
  tags:
    - mesos

# Add mesos repo
- name: add mesos repo
  sudo: yes
  apt_repository:
    repo: "deb http://repos.mesosphere.com/ubuntu trusty main"
  tags:
    - mesos

# Install mesos from repo
- name: install mesos
  sudo: yes
  apt:
    name: mesos=0.27.0-0.2.190.ubuntu1404
    force: yes
    update_cache: yes
  tags:
    - mesos

- name: ensure customized bin
  sudo: yes
  file:
    path: /opt/bin
    state: directory
  tags:
    - mesos

- name: config mesos master supervisord
  sudo: yes
  template: src=mesos_master_supervisord.conf.j2 dest=/etc/supervisord/mesos_master.conf
  notify: restart mesos master
  when: mesos_mode == "master"
  tags:
    - mesos

- name: config mesos slave supervisord
  sudo: yes
  template: src=mesos_slave_supervisord.conf.j2 dest=/etc/supervisord/mesos_slave.conf
  notify: restart mesos slave
  when: mesos_mode == "slave"
  tags:
    - mesos

- name: setup start_mesos_master script
  sudo: yes
  template:
    src: start_mesos_master.sh.j2
    dest: /opt/bin/start_mesos_master.sh
    mode: 0755
  notify: restart mesos master
  when: mesos_mode == "master"
  tags:
    - mesos

- name: setup start_mesos_slave script
  sudo: yes
  template:
    src: start_mesos_slave.sh.j2
    dest: /opt/bin/start_mesos_slave.sh
    mode: 0755
  notify: restart mesos slave
  when: mesos_mode == "slave"
  tags:
    - mesos

- name: start mesos master supervisord
  sudo: yes
  supervisorctl: 
    name: mesos_master 
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  when: mesos_mode == "master"
  tags:
    - mesos

- name: start mesos slave supervisord
  sudo: yes
  supervisorctl: 
    name: mesos_slave 
    state: present
    supervisorctl_path: "{{ supervisord_exec_dir }}/supervisorctl"
  when: mesos_mode == "slave"
  tags:
    - mesos
